package dev.nihilncunia.fa_campaign_manager.domains.characters;

import dev.nihilncunia.fa_campaign_manager.common.constant.YN_CODE;
import dev.nihilncunia.fa_campaign_manager.common.response.ResponseExampleBuilder;
import dev.nihilncunia.fa_campaign_manager.domains.characters.constant.CHARACTER_STATUS;
import dev.nihilncunia.fa_campaign_manager.domains.characters.dto.*;
import dev.nihilncunia.fa_campaign_manager.domains.sessions.SessionExample;
import dev.nihilncunia.fa_campaign_manager.domains.sessions.dto.SessionOutDto;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.time.OffsetDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class CharacterExample {
  private final ResponseExampleBuilder exampleBuilder;
  private final SessionExample sessionExample;
  
  @Getter
  private final CharacterOutDto characterFullData = CharacterOutDto.builder()
    .id(50L)
    .name("카엘")
    .status(CHARACTER_STATUS.ACTIVE).race("엘프")
    .startLevel(1)
    .startExp(0)
    .startCurrency(CharacterCurrencyDto.builder()
      .copper(10)
      .silver(5)
      .electrum(0)
      .gold(10)
      .platinum(0)
      .build())
    .currentLevel(7)
    .currentExp(15000)
    .currentCurrency(CharacterCurrencyDto.builder()
      .copper(45)
      .silver(120)
      .electrum(10)
      .gold(2500)
      .platinum(50)
      .build())
    .equipment(CharacterEquipmentDto.builder()
      .mainHand("엘븐 롱소드 +2")
      .offHand("미스릴 연을 본뜬 방패")
      .armor("강화된 사슬 갑옷")
      .head("통찰의 서클릿")
      .gauntlet("거인의 힘 장갑")
      .boots("차원 도약의 부츠")
      .belt("포션 수납용 가죽 벨트")
      .cloak("보호의 망토 +1")
      .accessory1("저항의 반지")
      .accessory2("언어 번역의 목걸이")
      .accessory3("공중 부양 귀걸이")
      .accessory4("마나 증폭 브로치")
      .build())
    .requirementStrDex(CharacterRequirementStrDexDto.builder()
      .reqStrDex8("휴대용 횃불")
      .reqStrDex10("모험가 배낭")
      .reqStrDex12("등반용 로프")
      .reqStrDex14("야영용 텐트")
      .reqStr16("대형 연금술 도구")
      .reqStr18("중장갑 보관함")
      .reqStr20("거대 괴수 유해")
      .build())
    .requirementCon(CharacterRequirementConDto.builder()
      .reqCon8("소형 물통")
      .reqCon10("식량 주머니")
      .reqCon12("보강된 장화")
      .reqCon14("철제 조리 도구")
      .reqCon16("방한용 침구")
      .reqCon18("그리핀 안장")
      .reqCon20("드래곤 전용 안장")
      .build())
    .classes(List.of(
      CharacterClassDto.builder()
        .className("Wizard")
        .subClass("Evocation")
        .level(7)
        .build()))
    .sessions(List.of(sessionExample.getSessionSimpleData()))
    .useYn(YN_CODE.Y)
    .deleteYn(YN_CODE.N)
    .creatorId(1L)
    .createDate(OffsetDateTime.now().minusWeeks(3))
    .updaterId(1L)
    .updateDate(OffsetDateTime.now().minusDays(2))
    .deleterId(null)
    .deleteDate(null)
    .build();
  
  @Getter
  private final CharacterOutDto characterSimpleData = CharacterOutDto.builder()
    .id(50L)
    .name("카엘")
    .status(CHARACTER_STATUS.ACTIVE).race("엘프")
    .startLevel(1)
    .startExp(0)
    .startCurrency(CharacterCurrencyDto.builder()
      .copper(10)
      .silver(5)
      .electrum(0)
      .gold(10)
      .platinum(0)
      .build())
    .currentLevel(7)
    .currentExp(15000)
    .currentCurrency(CharacterCurrencyDto.builder()
      .copper(45)
      .silver(120)
      .electrum(10)
      .gold(2500)
      .platinum(50)
      .build())
    .equipment(CharacterEquipmentDto.builder()
      .mainHand("엘븐 롱소드 +2")
      .offHand("미스릴 연을 본뜬 방패")
      .armor("강화된 사슬 갑옷")
      .head("통찰의 서클릿")
      .gauntlet("거인의 힘 장갑")
      .boots("차원 도약의 부츠")
      .belt("포션 수납용 가죽 벨트")
      .cloak("보호의 망토 +1")
      .accessory1("저항의 반지")
      .accessory2("언어 번역의 목걸이")
      .accessory3("공중 부양 귀걸이")
      .accessory4("마나 증폭 브로치")
      .build())
    .requirementStrDex(CharacterRequirementStrDexDto.builder()
      .reqStrDex8("휴대용 횃불")
      .reqStrDex10("모험가 배낭")
      .reqStrDex12("등반용 로프")
      .reqStrDex14("야영용 텐트")
      .reqStr16("대형 연금술 도구")
      .reqStr18("중장갑 보관함")
      .reqStr20("거대 괴수 유해")
      .build())
    .requirementCon(CharacterRequirementConDto.builder()
      .reqCon8("소형 물통")
      .reqCon10("식량 주머니")
      .reqCon12("보강된 장화")
      .reqCon14("철제 조리 도구")
      .reqCon16("방한용 침구")
      .reqCon18("그리핀 안장")
      .reqCon20("드래곤 전용 안장")
      .build())
    .classes(List.of(
      CharacterClassDto.builder()
        .className("Wizard")
        .subClass("Evocation")
        .level(7)
        .build()))
    .sessions(List.of())
    .useYn(YN_CODE.Y)
    .deleteYn(YN_CODE.N)
    .creatorId(1L)
    .createDate(OffsetDateTime.now().minusWeeks(3))
    .updaterId(1L)
    .updateDate(OffsetDateTime.now().minusDays(2))
    .deleterId(null)
    .deleteDate(null)
    .build();
}
